[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://ref.tradetrust.io"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "frame-ancestors 'none';"